### PR TITLE
Nwoc

### LINKED ISSUE #7: Implement search with country's capital names.

### PR DESCRIPTION
**Pull request by tejaswini22199**
### What is the change?
Changed the search based on capital name of country
fixes #7 
### What does it fix/add?
Added search by capital names users enter capital and country weather details are retrieved based on that

## Submissions guide:
- [yes] Have you followed the [Contribution guide](https://github.com/shelcia/Weather-app/blob/master/CONTRIBUTING.md)?
- [yes ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shelcia/Weather-app/pulls) for the same update/change?
- [ ] Have you made corresponding changes to the documentation?
- [yes] Your submission doesn't break any existing feature.
- [yes] Have you lint your code locally prior to submission?

### Screenshots (if appropriate):
Capture

### CODE REVIEW

**Comment by tejaswini22199** [comment]
hey shelcia could you please review my pr. I implemented the feature

**Comment by shelcia** [comment]
Hey the deployment will break if you don't the name of env variable as of original code. please make the change

**Comment by tejaswini22199** [comment]
hey @shelcia  can you review now

**Review by shelcia — CHANGES_REQUESTED** [review]
Make sure you do both for country name and capital with single input

**Pull request closed without merging**
